find_trending_companies:
  description: >
    Find the latest trending companies in {sector} by searching the latest news. Always find new companies 
    you've not found before.
  expected_output: >
    A list of trending companies in {sector}
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    Research the companies you found in the previous task. for each company you research for the informations
    which are relevant for the investment decision. Be very detailed and thorough and provide a comprehensive
    report about each company.
  expected_output: >
    A report about the companies you found.
  agent: financial_researcher
  output_file: output/research_report.md

pick_best_company:
  description: >
    Analyze the research findings and pick the best company for investment.
    Send a push notification to the user with the decision and 1 sentence rationale.
    Then respond with a detailed report on why you chose this company, and which companies were not selected.
  expected_output: >
    The chosen company and why it was chosen; the companies that were not selected and why they were not selected.
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
